version: '3'

services:
  marvelous_app_django:
    build: ./src/backend
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/backend:/code
    ports:
      - "8000:8000"

  marvelous_app_angular:
    build: ./src/frontend/project
    ports:
      - 80:80
    depends_on:
      - marvelous_app_django
